movies/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:movie_id>/', movie),
    path('movie_review/add/<int:movie_id>/', add_review),
    path('like/<int:movie_id>/', add_like),
    path('movie_reviews/<int:movie_id>/', movie_reviews, name='movie_reviews'),
    path('about/', about),
    path('mymovies/<int:users_id>/', my_movies),
    path("search/", search_movies, name="search_movies"),
    path("random/", random_movies, name="random_movies"),
    path("recommended/<int:movie_id>/", recommended_movies, name="random_movies"),
    path('', index)
]

mymovies/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('users/', include('users.urls')),
    path('', index, name='index')
]

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('', index, name='index'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length = 80)
    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length = 128)
    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length = 128)
    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length = 200)
    overview = models.TextField()
    release_date = models.DateField()
    running_time = models.IntegerField()
    budget = models.IntegerField(blank = True, null = True)
    tmdb_id = models.IntegerField(blank = True, null = True)
    revenue = models.IntegerField(blank = True, null = True)
    poster_path = models.URLField(blank = True, null = True)
    genres = models.ManyToManyField(Genre)
    credits = models.ManyToManyField(Person, through = 'MovieCredit')
    vote_average = models.IntegerField(blank = True, null = True)
    likes = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    def __str__(self):
        return f'{self.title} ({self.release_date})'
    
class MovieCredit(models.Model):
    person = models.ForeignKey(Person, on_delete = models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    job = models.ForeignKey(Job, on_delete = models.CASCADE)
    
class MovieReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.CharField(blank = True, null = True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    review = models.TextField(blank=True)
    title  = models.TextField(blank=False, null=False, default="Reseña sin titulo")

movies/forms.py
from django import forms


class MovieReviewForm(forms.Form):
    rating = forms.IntegerField(label="Calificacion", min_value=1, max_value=100, required=True)
    title = forms.CharField(label="Titulo", required=True)
    review = forms.CharField(label="Reseña", min_length=20, required=True)
    widget =  forms.Textarea(attrs={"class": "block w-full rounded-md bg-white px-3" 
                                  "py-1.5 text-base text-gray-900 outline outline-1"
                                  "-outline-offset-1 outline-gray-300 placeholder:text-zinc-400" 
                                  "focus:outline focus:outline-2 focus:-outline-offset-2" 
                                  "focus:outline-amber-400 sm:text-sm/6"})
    title.widget.attrs.update({"class": "py-1.5 pl-3 pr-2 block w-full rounded-md bg-white px-3" 
                                  "py-1.5 text-base text-zinc-900 outline outline-1"
                                  "focus:outline-amber-400 sm:text-sm/6"})
    rating.widget.attrs.update({"class": "rounded-md bg-white py-1.5 pl-3 pr-2 text-base text-zinc-900 outline outline-1 -outline-offset-1 outline-zinc-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-amber-400 sm:text-sm/6"})
    review.widget.attrs.update({"class": "py-1.5 pl-3 pr-2 block w-full rounded-md bg-white px-3" 
                                  "py-1.5 text-base text-zinc-900 outline outline-1"
                                  "focus:outline-amber-400 sm:text-sm/6"})

movies/views.py
from django.shortcuts import render
from django.http import HttpResponse
from movies.models import Movie, MovieReview
from movies.forms import MovieReviewForm
from datetime import date
from django.core.paginator import Paginator
from django.contrib.postgres import search
from django.contrib.auth import get_user_model
import random

# Create your views here.
def index(request):
    movies = list(Movie.objects.all())
    random_movies = []
    users = get_user_model().objects.all()
    print(users)
    if movies:
        random_movies= random.sample(movies,4)
    return render(request,'movies/index.html', {'movies': random_movies, 'users':users} )
    
def my_movies(request, users_id):
    movies = Movie.objects.all()
    selected_ids = []
    
    for movie in movies:
        id = movie.id
        reviewed_movie = MovieReview.objects.all().filter(user_id=users_id).values('movie_id').filter(movie_id=id)
        if reviewed_movie: selected_ids.append(reviewed_movie[0]['movie_id'])

    movies = movies.filter(id__in=selected_ids)
    
    context = { 'movies':movies, 'message':'welcome' }
    return render(request,'movies/index.html', context=context )

def movie(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    review_form = MovieReviewForm()
    context = { 'movie':movie, 'saludo':'welcome', "review_form":review_form }
    return render(request,'movies/movie.html', context=context )
    
def add_review(request, movie_id):
    form = None
    movie = Movie.objects.get(id=movie_id)
    if request.method == 'POST':
        form = MovieReviewForm(request.POST)
        left_review_already = MovieReview.objects.all().filter(user_id=request.user.id).values('movie_id').filter(movie_id=movie_id)
        if left_review_already:
            return render(request,
                  'movies/error_modal.html',
                  {'error_description': 'Ya creó una reseña para esta película anteriormente. Por favor intente con otra película o cuenta de usuario'})
        if form.is_valid():
            rating = form.cleaned_data['rating']
            title  = form.cleaned_data['title']
            review = form.cleaned_data['review']
            movie_review = MovieReview(
                    movie=movie,
                    rating=rating,
                    title=title,
                    review=review,
                    user=request.user,
                    date=date.today().strftime("%d/%m/%Y"))
            movie_review.save()
            return HttpResponse(status=204,
                                headers={'HX-Trigger': 'listChanged'})
        else:
            return render(request,
                  'movies/error_modal.html',
                  {'error_description': 'El formulario no es válido. Por favor intente denuevo'})
    else:
        form = MovieReviewForm()
        return render(request,
                  'movies/movie_review_form.html',
                  {'movie_review_form': form, 'movie':movie})
                  
def movie_reviews(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,'movies/reviews.html', context={'movie':movie } )
    
def about(request):
    return render(request,'movies/about.html' )
    
def add_like(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    movie.likes += 1
    movie.save()
        
    review_form = MovieReviewForm()
    context = { 'movie':movie, 'saludo':'welcome', "review_form":review_form }
    return render(request,'movies/movie.html', context=context )

def search_movies(request):
    if request.method == 'GET':
        value = request.GET['search']
        movies = ft_movies(value)

        paginator = Paginator(movies, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(request, 'movies/movies_search.html',
                      {'movies': movies, 'search_value': value,
                       "page_obj": page_obj})
    else:
        return render(request, 'movies/index.html',
                      {'movies': [], 'search_value': None})


def ft_movies(value):
    vector = (
        search.SearchVector("title", weight="A")
    )
    query = search.SearchQuery(value, search_type="websearch")
    return (
        Movie.objects.annotate(
            search=vector,
            rank=search.SearchRank(vector, query),
        )
        .filter(search=query)
        .order_by("-rank")
    )
    
def random_movies(request):
    movies = list(Movie.objects.all())
    random_movies = []
    if movies:
        random_movies = random.sample(movies, 4)
    return render(request, 'movies/movies_random.html',
                  {'movies': random_movies})
    
def recommended_movies(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    recommended_genres = []
    for genre in movie.genres.all():
        recommended_genres.append(genre)
    
    movies = list(Movie.objects.all())
    recommended_movies = []
    target_select = 4
    random.shuffle(movies)
    for movie in movies:
        if movie.id != movie_id:
            for genre in movie.genres.all():
                for recommended_genre in recommended_genres:
                    if genre == recommended_genre and target_select != 0:
                        target_select -= 1
                        recommended_movies.append(movie)
                        print(f"yes for {movie}, is now {target_select}")
                        break
                    break
            else:
                continue
            break
    
    if target_select != 0:
        recommended_movies.append(random.sample(movies, target_select)[0])
        
    print(recommended_movies)
    return render(request, 'movies/movies_random.html',
                  {'movies': recommended_movies})

movies/templates/movies/about.html
{% extends "movies/base.html" %}

{% block content %}
<div class="w-max mx-auto my-40 flex flex-col gap-y-14 font-mono">
    <div class="flex flex-col gap-y-3">
      <h1 class="text-amber-400 text-xl">Profesor :</h1>
      <p class="text-white ml-5">Jose Mario Garcia Valdez</p>
    </div>
    <div class="flex flex-col gap-y-3">
      <h1 class="text-amber-400 text-xl">Integrantes del equipo :</h1>
      <ul class="text-white ml-5">
        <li>Ramírez Castañeda Abner | <span class="text-amber-400">20211828</span></li>
        <li>Sámano Garduño Erick Adrian | <span class="text-amber-400">20211843</span></li>
        <li>Cruz Figueroa Valeria | <span class="text-amber-400">21210365</span></li>
      </ul>
    </div>
    <div class="flex flex-col gap-y-3">
      <h1 class="text-amber-400 text-xl">Datos obtenidos de :</h1>
      <a href="https://www.themoviedb.org/" target="_blank" class="block overflow-hidden w-[100px] ml-5">
        <img src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg" alt="">
      </a>
    </div>
  </div>
{% endblock content %}

movies/templates/movies/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'movies/icon.ico' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}

    {% endblock head %}
    <title>EIVOM</title>

      <script>
      /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
      </script>
  </head>

  <body class="bg-zinc-900" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block header %}
      {% include "movies/header.html" %} 
    {% endblock header %}


    {% block content %}



    {% endblock content %}
   
   


    {% block footer%}
<footer class="bg-zinc-800">
        <div class="mx-auto max-w-7xl overflow-hidden py-10 lg:px-8">
            <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-7" aria-label="Footer">
                <div>
                    <a href="
                    /movies/about
                    " class="text-sm leading-6 text-amber-400 font-mono hover:text-amber-300">Información</a>
                </div>
                <div>
                    <a href="https://github.com/AbnerRC1/MisPelis" target="_blank" class="text-sm leading-6 text-amber-400 font-mono hover:text-amber-300">GitHub</a>
                </div>
                <div>
                    <a href="https://www.themoviedb.org/" target="_blank" class="text-sm leading-6 text-amber-400 font-mono hover:text-amber-300">themoviedb.org</a>
                </div>
            </nav>
        
            <p class="mt-10 text-center text-xs leading-5 text-zinc-400 font-mono">&copy; 2024 | EIVOM</p>
        </div>
    </footer>

    {% endblock footer %}

  <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>

  {% block scripts %}

  {% endblock scripts %}

</body>
</html>

movies/templates/movies/error_modal.html
<div id="error_modal" _="on closeModal or listChanged remove me" class="relative z-100" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-zinc-900 bg-opacity-75 transition-opacity md:block"></div>
  <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
    <div class="flex w-full mx-auto transform
      text-left text-base transition
      md:my-8 md:max-w-2xl md:px-4 lg:max-w-4xl">
    
      <div class="relative flex w-full
              items-center overflow-hidden bg-zinc-800 rounded-lg  border-2 border-amber-400
              px-4 pb-8 pt-14 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
      
        <form class="bg-zinc-900 rounded-lg w-full md:col-span-2">
            <div class="px-4 py-3 sm:p-8">
              <div class="flex flex-row gap-x-2">
                <svg
                  class="fill-amber-400" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e8eaed">
                  <path d="M480-280q17 0 28.5-11.5T520-320q0-17-11.5-28.5T480-360q-17 0-28.5 11.5T440-320q0 17 11.5 28.5T480-280Zm-40-160h80v-240h-80v240Zm40 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z"/>
                </svg>
                <p class="block overflow-hidden
                        text-ellipsis mb-4 text-amber-400 text-xl font-bold font-mono">Se produjo un error</p>
              </div>
              
              <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                <div class="sm:col-span-4 font-mono text-white">
                  {{error_description}}
                </div>
              </div>
            <div class="mt-6 mr-3 flex items-center justify-end gap-x-2">
              <button type="button"  
                    _="on click trigger closeModal"
                      class="text-sm font-bolc text-amber-400 border-2 border-amber-400 px-3 py-2 rounded-lg font-mono">Cerrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

movies/templates/movies/index.html
{% extends "movies/base.html" %}
{% load static %}
{% block content %}

<div class="container mx-auto px-5 py-2 transition-all pb-12 lg:px-32 lg:pt-12">
  <div id="movies-container" class="-m-1 flex flex-wrap md:-m-2">
    {% for movie in movies %}
    <a href="/movies/{{movie.id}}" class="flex w-1/2 flex-wrap mt-3 transition-all border-2 border-amber-400 rounded-lg shadow-lg
            hover:scale-[1.02] sm:w-1/3 md:w-1/4">
      <div class="w-full relative">
        <div class="absolute bg-amber-400 z-10 top-2 left-2 rounded px-2 py-1 text-zinc-900 font-black text-xs shadow-md">{{movie.vote_average}}</div>
        <img
          class="block h-full w-full rounded-lg object-cover object-center saturate-0 transition-all hover:saturate-100"
          src="https://www.themoviedb.org/t/p/w600_and_h900_bestv2{{movie.poster_path}}" alt="{{movie.title}}" />
      </div>
      <div class="w-full mb-1">
        <p class="overflow-hidden text-ellipsis text-zinc-900 bg-amber-400 w-full mx-auto font-bold pl-2 font-mono">{{movie.title|truncatechars_html:40}}</p>
        <p href="#" class="block pl-2">
                        <span class="text-amber-400 text-sm font-thin font-mono">{{movie.release_date}}</span></p>
      </div>
    </a>
    {% empty %}
       <p class="text-zinc-400">No hay peliculas que presentar</p>
    {% endfor %}
  </div>
  {% if request.path == '/' %}
  <button class="flex w-48 mt-10 justify-center mx-auto rounded-lg
              bg-amber-400 px-3 py-1.5 text-sm font-bold leading-6 font-mono text-zinc-900
              shadow-sm hover:bg-amber-300 focus-visible:outline
              focus-visible:outline-2 focus-visible:outline-offset-2
              focus-visible:outline-zinc-900"
        hx-get="/movies/random" hx-target="#movies-container" hx-swap="beforeend"
    >Cargar más películas</button>
  <div class="flex flex-row flex-wrap gap-5">
    {% for user in users.all %}
    
    
    
    <div class="relative flex flex-col mt-4 flex items-center gap-x-4 transition-all hover:scale-[1.1]">
    <img src="{% static 'users/profile_photo.png' %}" alt="{{user.username}}" class="size-10 rounded-full bg-zinc-800">
    <div class="text-sm/6 flex gap-x-3">
      <p class="font-semibold text-white">
        <a href="movies/mymovies/{{user.id}}">
          <span class="absolute inset-0"></span>
          {{user}}
        </a>
      </p>
    </div>
  </div>
    
    
    
    {% empty %}
       <p class="text-zinc-400">No hay usuarios por el momento</p>
    {% endfor %}
  </div>
  {% endif %}

</div>
{% endblock content %}

movies/templates/movies/movie.html
{% extends "movies/base.html" %}


{% block content %}
<article>
 <div class="container flex flex-col gap-x-5 mx-auto px-5 py-2 pt-12 md:flex-row lg:px-32">
           <div class="overflow-hidden rounded-lg bg-zinc-800 shadow w-1/2 h-full mx-auto md:w-1/3 mr-auto">
             <div>
                 <div class="w-full p-1 md:p-2">
                   <img
                     class="block h-full w-full rounded-lg object-cover object-center"
              src="https://www.themoviedb.org/t/p/w600_and_h900_bestv2{{movie.poster_path}}" alt="{{movie.title}}" />
          </div>
      </div>
      <div class="bg-zinc-800 px-5">
                 <div  class="flex flex-col gap-y-2 pb-5 pt-2">
                   <p class="text-white font-thin font-mono">Datos de :</p>
            <a href="https://www.themoviedb.org/{{artwork.path}}" target="_blank" class="block overflow-hidden
                        text-ellipsis w-[100px]">
                        <img src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg" alt="TMDB logo">
                        </a>
          </div>
      </div>
    </div>
 <div class="overflow-hidden w-full h-full md:w-2/3">
    <div class="px-4 py-4 sm:px-6">
          <div  class="-m-1 mt-1 mb-5">
            <p class="block overflow-hidden
                             text-ellipsis text-white text-xl font-bold font-mono">{{movie.title}} ({{movie.release_date|date:"Y"}})</p>
                  <p class="mt-1 text-zinc-400 text-xs font-thin"> 
            {% for g in movie.genres.all %} 
            {{g}} 
            {% if not forloop.last %}
            -
            {% endif %}
            {%endfor%}</p>
            <div class="flex flex-row gap-x-5 mt-10">
            {% if user.is_authenticated %}
                <a class="border-2 border-amber-400 text-amber-400 rounded-full pl-3 pr-3 text-sm font-bold font-mono"   
                 hx-get="/movies/movie_review/add/{{movie.id}}" hx-target="body" hx-swap="beforeend"  href="#">Calificar</a> 
                 <div class="flex flex-row gap-x-2 bg-amber-400 rounded-full pt-0.5 pl-3 pr-3">
                            <a class="text-zinc-900 text-sm font-bold font-mono" href="/movies/like/{{movie.id}}">Me Gusta |</a>
                            <p class="mt-2text-gray-500 text-sm font-bold font-mono text-zinc-900">{{ movie.likes }}</p>
                        </div>
            {% endif %}
            </div> 
            
            <h1 class="mt-5 text-zinc-400 text-base font-semibold font-mono">Descripción :</h1>
            <p class="mt-2 text-zinc-400 text-sm font-normal font-mono">{{ movie.overview }}</p>
            <p class="mt-5 text-zinc-600 text-sm font-semibold font-mono"> Creditos :
               <p class="mt-2 text-zinc-600 text-sm font-thin font-mono">
              {% for c in movie.credits.all %} 
              {{c}} {% if not forloop.last %} - {% endif %}
              {%endfor%}  
              </p>
              <p class="block overflow-hidden mt-6 mb-3
                               text-ellipsis text-white text-xl font-bold font-mono">Reseñas :</p>
              <div hx-trigger="listChanged from:body" hx-get="{% url 'movie_reviews' movie.id  %}" hx-target="this" >
              {% include "movies/reviews.html" %}
            </div>
          </div>
      </div>
    </div>
 </div>
</article>






<section class="container flex flex-col gap-y-2 mx-auto px-5 transition-all pb-12 lg:px-32">
    <div class="bg-amber-zinc-900 border-2 border-amber-400 flex flex-row justify-between px-5 py-3 rounded-lg">
        <h1 class="block overflow-hidden text-amber-400 text-xl font-bold font-mono">Recomendaciones :</h1>
        <button class="rounded-lg bg-amber-400 w-14 h-10
              shadow-sm hover:bg-amber-200 focus-visible:outline
              focus-visible:outline-2 focus-visible:outline-offset-2
              focus-visible:outline-zinc-900"
            hx-get="/movies/recommended/{{movie.id}}" hx-target="#movies-container" hx-swap="beforeend">
                <svg
                    class="fill-zinc-900 scale-[2] mx-auto"
                    xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"><path d="M480-360 280-560h400L480-360Z"/>
                </svg>
            </button>
    </div>
    <div id="movies-container" class="-m-1 flex flex-wrap md:-m-2">
    </div>
</section>





{% endblock content %}

movies/templates/movies/movie_review_form.html
<div id="modal" _="on closeModal or listChanged remove me" 
    class="relative z-10" role="dialog" aria-modal="true">
  <div class="fixed inset-0 hidden bg-zinc-900 bg-opacity-75 transition-opacity md:block"></div>
        <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
<div class="flex w-full mx-auto transform 
            text-left text-base transition 
            md:my-8 md:max-w-2xl md:px-4 lg:max-w-4xl">
         
        <div class="relative flex w-full 
                items-center overflow-hidden bg-zinc-800 rounded-lg  border-2 border-amber-400
                px-4 pb-8 pt-14 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
          
        <form class="bg-zinc-900 rounded-lg w-full md:col-span-2" hx-post="/movies/movie_review/add/{{movie.id}}/" hx-target="#modal" hx-swap="outerHTML">
            <div class="px-4 py-3 sm:p-8">
                <p class="block overflow-hidden
                        text-ellipsis mb-4 text-amber-400 text-xl font-bold font-mono">Agrega una Reseña</p>
             <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-2">
                   <div class="font-mono text-white flex flex-col gap-y-5 sm:col-span-4">
                            {{movie_review_form}}
                          
                            <div class="text-sm font-medium text-amber-400 font-mono">
                                {{form.description.errors}}
                            </div>
                </div>
            </div>
         <div class="mt-6 mr-3 flex items-center justify-end gap-x-2">
            <button type="button"  
                    _="on click trigger closeModal" 
                    class="text-sm font-bolc text-amber-400 border-2 border-amber-400 px-3 py-2 rounded-lg font-mono">Cancelar</button>
            <button type="submit" class="rounded-md bg-amber-400 px-3 py-2 text-sm font-black text-zinc-900 shadow-sm font-mono hover:bg-amber-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-900">Guardar</button>
          </div>
        </form>
            </div>
        </div>
    </div>
        </div>
</div>

movies/templates/movies/reviews.html
{% load static %}
{% for review in movie.moviereview_set.all|dictsortreversed:"rating" %}
<article class="flex flex-col items-start justify-between pt-4 pb-6">
  <div class="relative mt-4 flex items-center gap-x-4">
    <img src="{% static 'users/profile_photo.png' %}" alt="{{user.username}}" class="size-10 rounded-full bg-zinc-800">
    <div class="text-sm/6 flex gap-x-3">
      <p class="font-semibold text-white">
        <a href="/movies/mymovies/{{review.user.id}}">
          <span class="absolute inset-0"></span>
          {{review.user}}
        </a>
      </p>
      <p class="text-zinc-600">Usuario desde {{review.user.date_joined|date:"M Y"}}</p>
    </div>
  </div>
  
  
  
  <div class="w-full flex flex-col gap-x-5">
      <div class="flex items-center gap-x-2 text-xs mt-2">
          <span class="relative z-10 rounded-full bg-amber-400 pl-1 pr-1 font-bold text-base text-zinc-900
          {% if review.rating < 30 %}
          bg-red-400
          {% elif review.rating > 70 %}
          bg-green-400
          {% else %}
          bg-amber-400
          {% endif %}">{{review.rating}}</span>
          <h3 class="text-lg/6 font-semibold text-white">
            {{review.title}}
          </h3>
        </div>
        <div class="group relative">
          <p class="mt-1 line-clamp-3 text-sm/6 text-zinc-400 bg-zinc-800 px-3 py-2 mt-3 rounded-lg">
              {{review.review}}
          </p>
        </div>
        <p class="text-zinc-600 text-sm text-right">{{review.date}}</p>
  </div>
</article> 
{% empty %}
   <p class="text-zinc-400">No hay reseñas todavía</p>
{% endfor %}